/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui;

/**
 *
 * @author ADMIN
 */
public class Complate extends javax.swing.JDialog {

    /**
     * Creates new form Complate
     */
    public Complate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public Complate(java.awt.Frame parent, boolean modal, String thuatToan, String thoiGian, int soBuoc) {
        super(parent, modal);
        initComponents();
        lblAlgorithmType.setText(thuatToan);
        lblTimes.setText(thoiGian);
        lblStep.setText(String.valueOf(soBuoc));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblStep = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAlgorithmType = new javax.swing.JLabel();
        lblTimes = new javax.swing.JLabel();
        lblStep2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chạy hoàn tất");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Thời gian:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 127, 35));

        lblStep.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblStep.setForeground(new java.awt.Color(0, 204, 255));
        lblStep.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblStep.setText("5");
        jPanel1.add(lblStep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 170, 35));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Số bước:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 127, 35));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Thuật toán:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 127, 35));

        lblAlgorithmType.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblAlgorithmType.setForeground(new java.awt.Color(0, 153, 51));
        lblAlgorithmType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAlgorithmType.setText("Đệ quy");
        jPanel1.add(lblAlgorithmType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 170, 35));

        lblTimes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTimes.setForeground(new java.awt.Color(204, 0, 0));
        lblTimes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTimes.setText("23s");
        jPanel1.add(lblTimes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, 35));

        lblStep2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblStep2.setForeground(new java.awt.Color(0, 204, 255));
        lblStep2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblStep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 320, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Complate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Complate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Complate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Complate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Complate dialog = new Complate(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlgorithmType;
    private javax.swing.JLabel lblStep;
    private javax.swing.JLabel lblStep2;
    private javax.swing.JLabel lblTimes;
    // End of variables declaration//GEN-END:variables
}
